### ISSUE TITLE
使用 kkFileView 作为文件预览扩展

### ISSUE THREAD

**Issue by cxplay** [cloudreve/Cloudreve#1020]
目前的的文件预览只能说是差强人意, 而且 Office 的预览经常出现问题, 如果没有完全从头开始支持和优化各种文件的预览的计划, 那么建议内置已有的解决办法.

kkFileView 目前已经使用 Apache 协议开源, 如果有可能还希望能够考虑一下:

> kkFileView - 在线文件预览: <https://kkfileview.keking.cn/zh-cn/docs/home.html>

**Comment by WEILAINIAO** [comment]
跪求，跪求，现在公司很多文档文件，几十台电脑的，无法分类和整理以及预览，跪求集成此插件！！！

**Comment by q601904795** [comment]
这东西需要java环境和openoffice.
按照cloudreve作者的风格来说,应该不会采纳这个建议.
毕竟目前cloudreve是单文件开箱即用的.

**Comment by WEILAINIAO** [comment]
要不网盘几千个文件，没法预览，都要一个一个下载以后打开来看，好奔溃啊！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月26日(星期天) 上午10:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cloudreve/Cloudreve] 使用 kkFileView 作为文件预览扩展 (#1020)





 
这东西需要java环境和openoffice.
 按照cloudreve作者的风格来说,应该不会采纳这个建议.
 毕竟目前cloudreve是单文件开箱即用的.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
